### ISSUE TITLE
1.50 to 1.53 bug in onSelectionChange causing to not work with function components and reset selection

### ISSUE THREAD

**Issue by kordeviant** [mbrn/material-table#1283]
**Describe the bug**
on 1.50 you can simply use onSelectionChange and set a state on wrapper component. 
but on 1.53 this setState causes selection checkboxes to become blank again.

you can check it here by simply changing version number on material table.
https://codesandbox.io/s/material-table-selection-different-data-from-table-lw9xs?fontsize=14

**Comment by masbaehr** [comment]
I also encountered this bug. rollback to 1.52 fixes it

**Comment by pradej** [comment]
While rollback to 1.52 does indeed fix it, I need some functionalities from 1.53 and it's not really an option :/

**Comment by masbaehr** [comment]
Note that the bug occurs only if you work with React states. So it is possible to work-around this if you rely on plain-javascript to do your onSelectionChange. Maybe it helps you to use 1.53 until a fix has been released. I'm doing it like that for now. Of course it's not pretty but it works ;-) 


```javascript
       onSelectionChange={(rows) => {
            console.log(rows);
            document.getElementById("selectionWorkaround").innerHTML = JSON.stringify(rows);
          }}
```


```javascript
       <div style={{display: 'none'}} id='selectionWorkaround'></div>
  function getSelectedItems(){
    var selection = JSON.parse(document.getElementById("selectionWorkaround").innerHTML);
    return selection;
  }
```

**Comment by pradej** [comment]
Since my selected state in wrapper component was not meant to re-render everything when changed, refactoring my code to
`const selectedItems = useRef([])` 
and
`onSelectionChange={rows => selectedItems.current = rows}`
solved the issue

**Comment by pradej** [comment]
While I could use `useRef` to store selected data (which is the correct way to do the above in React), this approach does not re-render on change. Sadly, I need re-rendering. I'll have to wait for a fix then

**Comment by ryanjohndunne** [comment]
I'm experiencing this issue as well. Can't set state of anything inside addSelectedRows or the selection boxes never get ticked and revert to an empty box.

**Comment by esjayrockz** [comment]
Which version was it last working on correctly? I have the issue even if I downgrade to 1.52.0 or 1.50.0

**Comment by pradej** [comment]
It started working again in 1.54.1

**Comment by esjayrockz** [comment]
Some people are reporting that they've been facing an issue in 1.54.1 as well, so am I.

**Comment by AkitoItashi** [comment]
Hi,

Sorry I just got you mails right now...
It worked in version 1.52.0 very well :3

Suvajit Chakrabarty <notifications@github.com> schrieb am Fr., 15. Nov.
2019, 18:57:

**Comment by kordeviant** [comment]
this is fixed somewhere along 1.54.
closed , good luck and thanks.

**Comment by eoghanmccarthy** [comment]
This issue still exists in 1.54.

**Comment by Roseidon** [comment]
@eoghanmccarthy can you provide an example where it doesn‘t work? Which version are you refering to exactly? 1.54.0 or a higher patch?

**Comment by eoghanmccarthy** [comment]
@Roseidon It's here where I'm attempting to set state:

```
onSelectionChange={selection => {
    setChecked(selection)
}}
```

And here are the packages:

react v16.12.0
material-ui/core v4.3.1
material-table v1.54.2

I tried downgrading to as low as material-table v1.40.0 but still no luck so that's why I was wondering if it was related to the version of React or maybe Material-ui.

**Comment by masbaehr** [comment]
still happening as of    "material-table": "^1.57.2",  under certain circumstances (which i did not yet find out ) this is a MAJOR issue and should be fixed before anything else

Duplicates: https://github.com/mbrn/material-table/issues/1307

**Comment by cmccann702** [comment]
Still experiencing this issue on 1.64.0

**Comment by chucksspencer** [comment]
Also still experiencing with 1.68.0

**Comment by chucksspencer** [comment]
Found a workaround in the thread for #1265 [(this comment)](https://github.com/mbrn/material-table/issues/1265#issuecomment-618288781) - lifting the data into the state for the parent component does the trick.

**Comment by zachrickards** [comment]
> Found a workaround in the thread for #1265 [(this comment)](https://github.com/mbrn/material-table/issues/1265#issuecomment-618288781) - lifting the data into the state for the parent component does the trick.

This needs to be fixed, that should not be the solution
